import type { ESGInputs, Narratives } from "@/lib/esg/types";

export const emptyInputs: ESGInputs = {
  companyName: "",
  industry: "",
  reportYear: 2026,
  foundedYear: 2020,
  revenueMil: 0,
  employees: 0,
  electricityKwh: 0,
  lngM3: 0,
  dieselL: 0,
  gasolineL: 0,
  lpgKg: 0,
  waterTon: 0,
  wasteTon: 0,
  renewableKwh: 0,
  femaleEmployees: 0,
  newHires: 0,
  injuries: 0,
  trainingHours: 0,
  socialContributionMil: 0,
  supplierAudits: 0,
  boardMembers: 0,
  outsideDirectors: 0,
  femaleDirectors: 0,
  boardMeetings: 0,
  ethicsCode: false,
  esgDisclosure: "미공개",
};

export const scenarioInputs: ESGInputs = {
  companyName: "충남정밀㈜",
  industry: "제조업",
  reportYear: 2026,
  foundedYear: 2014,
  revenueMil: 12000,
  employees: 48,
  electricityKwh: 240000,
  lngM3: 18000,
  dieselL: 9000,
  gasolineL: 3000,
  lpgKg: 1200,
  waterTon: 3500,
  wasteTon: 42,
  renewableKwh: 12000,
  femaleEmployees: 17,
  newHires: 6,
  injuries: 1,
  trainingHours: 24,
  socialContributionMil: 30,
  supplierAudits: 8,
  boardMembers: 7,
  outsideDirectors: 3,
  femaleDirectors: 2,
  boardMeetings: 11,
  ethicsCode: true,
  esgDisclosure: "공개",
};

export const emptyNarratives: Narratives = {
  environment: "",
  social: "",
  governance: "",
};
